name: CMake Build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up CMake
        uses: jwlawson/actions-setup-cmake@v1
        with:
          cmake-version: '3.21.0'

      - name: Create build directory
        run: |
          mkdir build
          cd build

      - name: Set up CMake
        run: 
          cmake ..
          cmake --build .

      - name: Run tests
        run: ctest --output-on-failure --test-dir build

